### ISSUE TITLE
Ability to patch, non Git repositories

### ISSUE THREAD

**Issue by jamierocks** [Minecrell/gitpatcher#1]
eg decompiled minecraft. like forge

**Comment by stephan-gh** [comment]
How would this work? gitpatcher generates and applies patches in form of commits. A Git repo to apply the commits on will be always needed. You could theoretically initialize an empty repo on the decompiled source, whether this will be really worth it at the end is questionable. ForgeGradle's patcher plugin is better designed for this.

**Comment by jamierocks** [comment]
Oh right. /me forgot that existed

**Comment by stephan-gh** [comment]
Can I close this issue then?

**Comment by jamierocks** [comment]
Yeah sure.
