### ISSUE TITLE
Patches contain user specific version

### ISSUE THREAD

**Issue by LexManos** [Minecrell/gitpatcher#4]
The last line of each patch is the user specific git executable version number.
Not a big issue, just a reminder mainly as it's change spam in patch updates.

**Comment by stephan-gh** [comment]
If someone wants to implement this my suggestion would be to use options like introduced in https://github.com/PaperMC/Paper/pull/2324:

```
Add --zero-commit --full-index --no-signature to git format-patch
to reduce the diff when doing minor changes in patches.

 --zero-commit: Print 00000000... commit hash in first "From" line
   of the patch. This commit hash is useless because it changes
   every time the patch is applied.

 --full-index: Print full SHA-1 hash on "index aaaa..bbbb" lines.
   This makes the lines much longer, but avoids random changes to
   add/remove a character based on the number of objects that exist
   in the local repository.

 --no-signature: Omit Git version from generated patches.
```

I suspect it should be simple to add them here:

https://github.com/CadixDev/gitpatcher/blob/f05f2128dee7356e1119c3b4e045cf04ed4d7c02/src/main/groovy/net/minecrell/gitpatcher/task/patch/MakePatchesTask.groovy#L75

**Comment by jamierocks** [comment]
Alright I've put together https://github.com/CadixDev/gitpatcher/commit/2810723622512f9258d91ef5e4f22d048ff6a3ba to resolve this, which would look something like:

```gradle
patches {
    submodule = 'upstream'
    target = file('target')
    patches = file('patches')

    zeroCommit = true
    fullIndex = true
    noSignature = true
}
```

Though as I'm writing this comment I think allowing users to use any extra arguments they like may be the better solution, so I would be open to implementing the following

```gradle
patches {
    submodule = 'upstream'
    target = file('target')
    patches = file('patches')

    extraArgs = ['--zero-commit', '--full-index', '--no-signature']
}
```

I'm leaning towards the latter right now, but would love some input on it :)

*edit*: another discussion to have is about defaults.

**Comment by jamierocks** [comment]
Okay, so I discussed this with @Minecrell and using the second option (control over the exact arguments used), we've set the default `formatPatchArgs` to `['--no-stat', '-N']` (which we previously applied).

This can be expanded upon like the following:
```gradle
patches {
    submodule = 'upstream'
    target = file('target')
    patches = file('patches')

    formatPatchArgs += ['--zero-commit', '--full-index', '--no-signature']
}
```
